{% set name = "python-jenkins" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56e7dabb0607bdb8e1d6fc6d2d4301abedbed9165da2b206facbd3071cb6eecb

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pbr >=0.8.2
    - pip
    - python >=3.4
  run:
    - multi_key_dict
    - python >=3.4
    - requests
    - setuptools <66 # requires pkg_resources at runtime
    - pbr >=0.8.2  # in upstream requirements.txt; needed by pip check
    - six >=1.3.0

test:
  imports:
    - jenkins
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://git.openstack.org/cgit/openstack/python-jenkins
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Python Jenkins is a python wrapper for the Jenkins REST API

extra:
  recipe-maintainers:
    - nicoddemus
