{% set name = "python-jenkins" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: deed8fa79d32769a615984a5dde5e01eda04914d3f4091bd9a23d30474695106

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pbr >=0.8.2
    - pip
    - python
  run:
    - multi_key_dict
    - python
    - requests
    - setuptools  # requires pkg_resources at runtime
    - six >=1.3.0

test:
  imports:
    - jenkins

about:
  home: http://git.openstack.org/cgit/openstack/python-jenkins
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Python Jenkins is a python wrapper for the Jenkins REST API

extra:
  recipe-maintainers:
    - nicoddemus
